import type { Metadata } from 'next';
import './globals.css';
import { Toaster } from 'react-hot-toast';
import TanstackProvider from '@/lib/provider/tanstack-provider';
import MiniSideCallout from '@/components/MiniSideCallout';
import { GoogleTagManager } from '@next/third-parties/google';

export const metadata: Metadata = {
	title: 'Dum Dum Krishna Kumar Hindu Academy Alumni Association',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<GoogleTagManager
				gtmId={process.env.NEXT_PUBLIC_GOOGLE_TAG_MANAGER_ID!}
			/>
			<body>
				<TanstackProvider>
					{children}
					<MiniSideCallout />
				</TanstackProvider>
				<Toaster />
			</body>
		</html>
	);
}
